# Generated by Django 4.1.7 on 2023-06-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_author_blogpost_model_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='model_post',
            field=models.CharField(default='Not Added', max_length=10000),
        ),
    ]
