# Generated by Django 4.1.7 on 2023-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blogpost_model_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='model_like',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
