# Generated by Django 4.1.7 on 2023-06-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blogpost_blog_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='model_author',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='id',
            new_name='model_id',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_desc',
            new_name='model_post',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='short_desc',
            new_name='model_short',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_title',
            new_name='model_title',
        ),
    ]
