# Generated by Django 4.1.7 on 2023-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blogpost_model_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='model_author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='model_short',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='model_title',
            field=models.CharField(max_length=500),
        ),
    ]
