# Generated by Django 4.1.7 on 2023-07-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blogpost_model_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='model_like',
            field=models.IntegerField(default=0),
        ),
    ]
