# Generated by Django 4.1.7 on 2023-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blogpost_model_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='model_recent_short',
            field=models.CharField(default='NA', max_length=150),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='model_recent_title',
            field=models.CharField(default='NA', max_length=500),
        ),
    ]
