# Generated by Django 4.1.7 on 2023-07-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blogpost_model_recent_short_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='model_recent_short',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='model_recent_title',
        ),
    ]
