# Generated by Django 4.1.7 on 2023-07-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_blogpost_model_recent_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
