# Generated by Django 4.1.7 on 2023-07-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_blogpost_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='last_visit',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
