# Generated by Django 4.1.7 on 2023-07-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_blogpost_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
    ]
